name: Fly Deploy
on:
  push:
    branches:
      - production
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy ./jotter-server -e DBS_HOST=${{ secrets.DBS_HOST }} -e DBS_NAME=${{ secrets.DBS_NAME }} -e DBS_PASSWORD=${{ secrets.DBS_PASSWORD }} -e DBS_USERNAME=${{ secrets.DBS_USERNAME }} -e PROFILE=${{ secrets.PROFILE }} --remote-only
